import "~/styles/globals.css";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <main className="flex min-h-screen w-screen flex-col items-center bg-gradient-to-b from-[#16234c] to-[#1d1c1f] font-mono text-white">
          <div className="container flex flex-col gap-6 px-4 py-8 md:gap-12 md:py-16">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
